# Generated by Django 5.2 on 2025-05-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprtal',
            name='types',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
