# Generated by Django 5.2 on 2025-05-16 14:29

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0003_studentprtal_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprtal',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='dmanour/Studentportal/'),
        ),
    ]
