# Generated by Django 5.2 on 2025-06-20 22:30

import cloudinary_storage.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0005_alter_studentprtal_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPortalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='damanhour/Studentportal/multiple/')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='studentportal.studentprtal')),
            ],
        ),
    ]
