# Generated by Django 5.2 on 2025-04-26 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_title', models.CharField(max_length=255)),
                ('en_title', models.CharField(max_length=255)),
                ('ar_description', models.TextField(blank=True, null=True)),
                ('en_description', models.TextField(blank=True, null=True)),
                ('ar_content', models.TextField()),
                ('en_content', models.TextField()),
                ('ar_keywords', models.JSONField(blank=True, default=list, null=True)),
                ('en_keywords', models.JSONField(blank=True, default=list, null=True)),
                ('ar_source', models.CharField(blank=True, max_length=255, null=True)),
                ('en_source', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ar_new_type', models.CharField(choices=[('اعلان', 'اعلان'), ('حدث', 'حدث'), ('خبر', 'خبر')], max_length=20)),
                ('en_new_type', models.CharField(choices=[('ad', 'advertisement'), ('event', 'event'), ('new', 'new')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_event', models.BooleanField(default=False)),
                ('month', models.PositiveIntegerField(blank=True, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_link', models.URLField(blank=True, null=True)),
                ('units', models.ManyToManyField(related_name='news', to='units.unit')),
            ],
        ),
        migrations.CreateModel(
            name='NewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/images/')),
                ('news_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.newsarticle')),
            ],
        ),
        migrations.CreateModel(
            name='NewsPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='news/pdfs/')),
                ('news_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='news.newsarticle')),
            ],
        ),
        migrations.CreateModel(
            name='NewVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='news/videos/')),
                ('news_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='news.newsarticle')),
            ],
        ),
    ]
