# Generated by Django 5.2 on 2025-04-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsarticle_units'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='units',
            field=models.ManyToManyField(related_name='news', to='units.unit'),
        ),
    ]
