# Generated by Django 5.2 on 2025-05-15 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newsarticle_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticle',
            old_name='ar_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='newsarticle',
            old_name='ar_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='newsarticle',
            old_name='ar_keywords',
            new_name='keywords',
        ),
        migrations.RenameField(
            model_name='newsarticle',
            old_name='ar_source',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='newsarticle',
            old_name='ar_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='en_content',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='en_description',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='en_keywords',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='en_new_type',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='en_source',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='en_title',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='units',
        ),
    ]
