# Generated by Django 5.2 on 2025-05-16 14:29

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_ar_content_newsarticle_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newimage',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='damanhour/news/images/'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='damanhour/news/main_images/'),
        ),
        migrations.AlterField(
            model_name='newspdf',
            name='pdf',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='damanhour/news/pdfs/'),
        ),
        migrations.AlterField(
            model_name='newvideo',
            name='video',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='damanhour/news/videos/'),
        ),
    ]
