# Generated by Django 5.2 on 2025-05-18 10:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_newimage_image_alter_newsarticle_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newvideo',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
