# Generated by Django 5.2 on 2025-04-26 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='secyion',
            new_name='section',
        ),
    ]
