# Generated by Django 5.2 on 2025-05-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_secyion_services_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='acadmic_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255, unique=True)),
                ('leacture_schedule', models.FileField(blank=True, null=True, upload_to='acadmic_years/leacture_schedule/')),
                ('partical_exam', models.FileField(blank=True, null=True, upload_to='acadmic_years/partical_exam/')),
                ('exam', models.FileField(blank=True, null=True, upload_to='acadmic_years/exam/')),
                ('seating_number', models.FileField(blank=True, null=True, upload_to='acadmic_years/seating_number/')),
            ],
        ),
        migrations.RenameField(
            model_name='section',
            old_name='biography_link',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='section',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='section',
            name='message',
        ),
        migrations.RemoveField(
            model_name='section',
            name='organizational_structure',
        ),
        migrations.RemoveField(
            model_name='section',
            name='page',
        ),
        migrations.RemoveField(
            model_name='section',
            name='speech',
        ),
        migrations.RemoveField(
            model_name='section',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='section',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='section/'),
        ),
        migrations.AddField(
            model_name='section',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='services',
        ),
    ]
