# Generated by Django 5.2 on 2025-05-16 14:29

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_acadmic_year_rename_biography_link_section_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acadmic_year',
            name='leacture_schedule',
        ),
        migrations.RemoveField(
            model_name='acadmic_year',
            name='partical_exam',
        ),
        migrations.AddField(
            model_name='acadmic_year',
            name='lecture_schedule',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='damanhour/academic_years/lecture_schedule/'),
        ),
        migrations.AddField(
            model_name='acadmic_year',
            name='practical_exam',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='damanhour/academic_years/practical_exam/'),
        ),
        migrations.AlterField(
            model_name='acadmic_year',
            name='exam',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='damanhour/academic_years/exam/'),
        ),
        migrations.AlterField(
            model_name='acadmic_year',
            name='seating_number',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='damanhour/academic_years/seating_number/'),
        ),
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='damanhour/Section/images/'),
        ),
        migrations.AlterField(
            model_name='section',
            name='pdf',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='damanhour/Section/pdfs/'),
        ),
    ]
