# Generated by Django 5.2 on 2025-05-21 18:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_acadmic_year_leacture_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acadmic_year',
            name='exam',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='acadmic_year',
            name='lecture_schedule',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='acadmic_year',
            name='practical_exam',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='acadmic_year',
            name='seating_number',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='pdf',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
