# Generated by Django 5.2 on 2025-05-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('users', '0003_staff_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='assisting_department', to='users.staff'),
        ),
    ]
