# Generated by Django 5.2 on 2025-05-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_department_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialprogram',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='SpecialProgram/'),
        ),
    ]
