# Generated by Django 5.2 on 2025-05-16 14:29

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_specialprogram_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='damanhour/department/images/'),
        ),
        migrations.AlterField(
            model_name='department',
            name='pdf',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='damanhour/department/pdfs/'),
        ),
        migrations.AlterField(
            model_name='mastersprogram',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='damanhour/Masters_Program/images/'),
        ),
        migrations.AlterField(
            model_name='specialprogram',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='damanhour/Special_Program/images/'),
        ),
    ]
