# Generated by Django 5.2 on 2025-04-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visionmission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/faculty_info/'),
        ),
    ]
