# Generated by Django 5.2 on 2025-05-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='status',
        ),
    ]
