# Generated by Django 5.2 on 2025-05-16 12:42

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeleaders',
            name='cv',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cv'),
        ),
        migrations.AlterField(
            model_name='collegeleaders',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='visionmission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='faculty_info/'),
        ),
    ]
