# Generated by Django 5.2 on 2025-05-16 13:07

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_collegeleaders_cv_alter_collegeleaders_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeleaders',
            name='cv',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='collegeleaders',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=''),
        ),
    ]
