# Generated by Django 5.2 on 2025-05-16 14:29

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_collegeleaders_cv_alter_collegeleaders_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeleaders',
            name='cv',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='damanhour/college-leaders/cv/'),
        ),
        migrations.AlterField(
            model_name='collegeleaders',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='damanhour/college-leaders/images/'),
        ),
        migrations.AlterField(
            model_name='facultyinfo',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='damanhour/faculty-info/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='damanhour/sliders/'),
        ),
        migrations.AlterField(
            model_name='visionmission',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='damanhour/vision-mission/'),
        ),
    ]
