# Generated by Django 5.2 on 2025-05-16 18:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_collegeleaders_cv_alter_collegeleaders_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeleaders',
            name='cv',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='damanhour/college-leaders/cv/'),
        ),
        migrations.AlterField(
            model_name='collegeleaders',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='damanhour/college-leaders/images/'),
        ),
        migrations.AlterField(
            model_name='facultyinfo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='damanhour/faculty-info/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='damanhour/sliders/'),
        ),
        migrations.AlterField(
            model_name='visionmission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='damanhour/vision-mission/'),
        ),
    ]
