# Generated by Django 5.2 on 2025-05-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_collegeleaders_cv_alter_collegeleaders_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeleaders',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='Collegeleaders/'),
        ),
        migrations.AlterField(
            model_name='collegeleaders',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Collegeleaders/'),
        ),
        migrations.AlterField(
            model_name='facultyinfo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='start_your_future/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quick_services/'),
        ),
        migrations.AlterField(
            model_name='visionmission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/faculty_info/'),
        ),
    ]
