# Generated by Django 5.2 on 2025-05-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_pdf_collegeleaders_cv'),
    ]

    
    
