# Generated by Django 5.2 on 2025-05-17 14:40

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_collegeleaders_cv_collegeleaders_cv_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegeleaders',
            name='cv_link',
        ),
        migrations.AddField(
            model_name='collegeleaders',
            name='cv',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='damanhour/Collegeleaders/pdfs/'),
        ),
    ]
