# Generated by Django 5.2 on 2025-05-17 21:00

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_collegeleaders_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyinfo',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='damanhour/FacultyInfo/pdfs/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='damanhour/slider/images/'),
        ),
        migrations.AlterField(
            model_name='visionmission',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='damanhour/VisionMission/images/'),
        ),
    ]
