# Generated by Django 5.2 on 2025-05-18 10:06

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_facultyinfo_video_alter_slider_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyinfo',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=''),
        ),
    ]
