# Generated by Django 5.2 on 2025-05-18 10:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_facultyinfo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyinfo',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
