# Generated by Django 5.2 on 2025-06-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_slider_image_slider_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeleaders',
            name='cv',
            field=models.URLField(blank=True, null=True),
        ),
    ]
