# Generated by Django 5.2 on 2025-05-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
        ('users', '0005_alter_graduation_cv_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitservice',
            old_name='description',
            new_name='abou_unit',
        ),
        migrations.RenameField(
            model_name='unitservice',
            old_name='page',
            new_name='unit_objectives',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='biography_link',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='message',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='organizational_structure',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='page',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='speech',
        ),
        migrations.RemoveField(
            model_name='unitservice',
            name='link',
        ),
        migrations.RemoveField(
            model_name='unitservice',
            name='name',
        ),
        migrations.AddField(
            model_name='unitservice',
            name='orgnization_structure',
            field=models.ManyToManyField(blank=True, related_name='unit_services', to='users.staff'),
        ),
    ]
