# Generated by Django 5.2 on 2025-05-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_rename_description_unitservice_abou_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitservice',
            name='abou_unit',
        ),
        migrations.AddField(
            model_name='unitservice',
            name='about_unit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
