# Generated by Django 5.2 on 2025-04-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_staff_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(default=1, upload_to='users/staff/'),
            preserve_default=False,
        ),
    ]
