# Generated by Django 5.2 on 2025-05-04 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_department_doctors'),
        ('users', '0003_staff_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='appointment_type',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='disbursement_id',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='google_schoolar',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='key_user',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='primary_appointment_group',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='related_unit',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='researches',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='status',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='x',
        ),
        migrations.AddField(
            model_name='staff',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('graduation', 'Graduation'), ('', 'None')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='staff_cvs/'),
        ),
        migrations.RemoveField(
            model_name='staff',
            name='department',
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staff_images/'),
        ),
        migrations.CreateModel(
            name='Graduation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('employment_status', models.CharField(blank=True, max_length=100)),
                ('job_name', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_phone', models.CharField(blank=True, max_length=20)),
                ('company_link', models.URLField(blank=True)),
                ('about_company', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.ManyToManyField(blank=True, related_name='staffs', to='academics.department'),
        ),
    ]
