# Generated by Django 5.2 on 2025-05-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduation',
            name='cv',
            field=models.FileField(default=11, upload_to='cvs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graduation',
            name='employment_status',
            field=models.CharField(choices=[('employee', 'Employee'), ('unemployee', 'Unemployee'), ('freelance', 'Freelance'), ('postgraduate', 'Postgraduate Studies')], max_length=100),
        ),
    ]
