# Generated by Django 5.2 on 2025-05-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_rename_description_unitservice_abou_unit_and_more'),
        ('users', '0005_alter_graduation_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='unit',
            field=models.ManyToManyField(blank=True, related_name='staffs', to='units.unit'),
        ),
    ]
