# Generated by Django 5.2 on 2025-05-15 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_staff_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='unit',
            new_name='units',
        ),
    ]
