# Generated by Django 5.2 on 2025-05-17 21:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_staff_cv_alter_staff_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='cv',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
