# Generated by Django 5.2 on 2025-05-18 09:58

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_staff_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='cv',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='damanhour/staff_cvs/'),
        ),
    ]
