# Generated by Django 5.2 on 2025-05-20 12:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_staff_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduation',
            name='cv',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
