# Generated by Django 5.2 on 2025-06-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_customuser_user_type_remove_graduation_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduation',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
