# Generated by Django 5.2 on 2025-06-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_graduation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduation',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
