# Generated by Django 5.2 on 2025-06-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_graduation_is_active_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduation',
            name='employment_status',
            field=models.CharField(choices=[('employee', 'موظف'), ('unemployee', 'غير موظف'), ('freelance', 'يعمل عمل حر'), ('postgraduate', 'طالب دراسات عليا'), ('seeking_job', 'باحث عن عمل')], max_length=100),
        ),
    ]
