# Generated by Django 5.2 on 2025-06-10 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_graduation_employment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='graduation',
            name='password',
        ),
        migrations.RemoveField(
            model_name='graduation',
            name='username',
        ),
        migrations.AddField(
            model_name='graduation',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='graduation_info', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
