# Generated by Django 5.2 on 2025-06-11 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_graduation_email_remove_graduation_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduation',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graduation',
            name='username',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graduation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graduation', to=settings.AUTH_USER_MODEL),
        ),
    ]
